#####
# Creates lattice grid/facet plot from the data generated by alt_facetdata.py - facetdata<x>.txt where <x> xorresponds to the data folder
# Requires alt_facetdata.py to be executed first
#####
library('ggplot2')

df4 <- read.table("facet_data.txt", header = TRUE)
# head(df4)
ggplot(df4,aes(x=MoI,y=P.lyso.)) + geom_line() + facet_grid(p2~p1)